let jewelleryData={
    "Rings Data": [
        {
            "Product ID": "RI1001",
            "Name": "Rings Design 1",
            "Category": "Rings",
            "Material": "Material 1",
            "Gemstone": "Gemstone 1",
            "Color": "Color 1",
            "Size": "Size 1",
            "Price": "$10.00",
            "Quantity": "Quantity 1",
            "SKU": "SKU 1",
            "Brand": "Brand 1",
            "Collection": "Collection 1",
            "Style": "Style 1",
            "Occasion": "Occasion 1",
            "Gender": "Gender 1",
            "Weight": "Weight 1",
            "Dimension": "Dimension 1",
            "Discount": "Discount 1",
            "Rating": "Rating 1",
            "Review Count": "Review Count 1"
        },
        {
            "Product ID": "RI1002",
            "Name": "Rings Design 2",
            "Category": "Rings",
            "Material": "Material 2",
            "Gemstone": "Gemstone 2",
            "Color": "Color 2",
            "Size": "Size 2",
            "Price": "$11.00",
            "Quantity": "Quantity 2",
            "SKU": "SKU 2",
            "Brand": "Brand 2",
            "Collection": "Collection 2",
            "Style": "Style 2",
            "Occasion": "Occasion 2",
            "Gender": "Gender 2",
            "Weight": "Weight 2",
            "Dimension": "Dimension 2",
            "Discount": "Discount 2",
            "Rating": "Rating 2",
            "Review Count": "Review Count 2"
        },
        {
            "Product ID": "RI1003",
            "Name": "Rings Design 3",
            "Category": "Rings",
            "Material": "Material 3",
            "Gemstone": "Gemstone 3",
            "Color": "Color 3",
            "Size": "Size 3",
            "Price": "$12.00",
            "Quantity": "Quantity 3",
            "SKU": "SKU 3",
            "Brand": "Brand 3",
            "Collection": "Collection 3",
            "Style": "Style 3",
            "Occasion": "Occasion 3",
            "Gender": "Gender 3",
            "Weight": "Weight 3",
            "Dimension": "Dimension 3",
            "Discount": "Discount 3",
            "Rating": "Rating 3",
            "Review Count": "Review Count 3"
        },
        {
            "Product ID": "RI1004",
            "Name": "Rings Design 4",
            "Category": "Rings",
            "Material": "Material 4",
            "Gemstone": "Gemstone 4",
            "Color": "Color 4",
            "Size": "Size 4",
            "Price": "$13.00",
            "Quantity": "Quantity 4",
            "SKU": "SKU 4",
            "Brand": "Brand 4",
            "Collection": "Collection 4",
            "Style": "Style 4",
            "Occasion": "Occasion 4",
            "Gender": "Gender 4",
            "Weight": "Weight 4",
            "Dimension": "Dimension 4",
            "Discount": "Discount 4",
            "Rating": "Rating 4",
            "Review Count": "Review Count 4"
        },
        {
            "Product ID": "RI1005",
            "Name": "Rings Design 5",
            "Category": "Rings",
            "Material": "Material 5",
            "Gemstone": "Gemstone 5",
            "Color": "Color 5",
            "Size": "Size 5",
            "Price": "$14.00",
            "Quantity": "Quantity 5",
            "SKU": "SKU 5",
            "Brand": "Brand 5",
            "Collection": "Collection 5",
            "Style": "Style 5",
            "Occasion": "Occasion 5",
            "Gender": "Gender 5",
            "Weight": "Weight 5",
            "Dimension": "Dimension 5",
            "Discount": "Discount 5",
            "Rating": "Rating 5",
            "Review Count": "Review Count 5"
        },
        {
            "Product ID": "RI1006",
            "Name": "Rings Design 6",
            "Category": "Rings",
            "Material": "Material 6",
            "Gemstone": "Gemstone 6",
            "Color": "Color 6",
            "Size": "Size 6",
            "Price": "$15.00",
            "Quantity": "Quantity 6",
            "SKU": "SKU 6",
            "Brand": "Brand 6",
            "Collection": "Collection 6",
            "Style": "Style 6",
            "Occasion": "Occasion 6",
            "Gender": "Gender 6",
            "Weight": "Weight 6",
            "Dimension": "Dimension 6",
            "Discount": "Discount 6",
            "Rating": "Rating 6",
            "Review Count": "Review Count 6"
        },
        {
            "Product ID": "RI1007",
            "Name": "Rings Design 7",
            "Category": "Rings",
            "Material": "Material 7",
            "Gemstone": "Gemstone 7",
            "Color": "Color 7",
            "Size": "Size 7",
            "Price": "$16.00",
            "Quantity": "Quantity 7",
            "SKU": "SKU 7",
            "Brand": "Brand 7",
            "Collection": "Collection 7",
            "Style": "Style 7",
            "Occasion": "Occasion 7",
            "Gender": "Gender 7",
            "Weight": "Weight 7",
            "Dimension": "Dimension 7",
            "Discount": "Discount 7",
            "Rating": "Rating 7",
            "Review Count": "Review Count 7"
        },
        {
            "Product ID": "RI1008",
            "Name": "Rings Design 8",
            "Category": "Rings",
            "Material": "Material 8",
            "Gemstone": "Gemstone 8",
            "Color": "Color 8",
            "Size": "Size 8",
            "Price": "$17.00",
            "Quantity": "Quantity 8",
            "SKU": "SKU 8",
            "Brand": "Brand 8",
            "Collection": "Collection 8",
            "Style": "Style 8",
            "Occasion": "Occasion 8",
            "Gender": "Gender 8",
            "Weight": "Weight 8",
            "Dimension": "Dimension 8",
            "Discount": "Discount 8",
            "Rating": "Rating 8",
            "Review Count": "Review Count 8"
        },
        {
            "Product ID": "RI1009",
            "Name": "Rings Design 9",
            "Category": "Rings",
            "Material": "Material 9",
            "Gemstone": "Gemstone 9",
            "Color": "Color 9",
            "Size": "Size 9",
            "Price": "$18.00",
            "Quantity": "Quantity 9",
            "SKU": "SKU 9",
            "Brand": "Brand 9",
            "Collection": "Collection 9",
            "Style": "Style 9",
            "Occasion": "Occasion 9",
            "Gender": "Gender 9",
            "Weight": "Weight 9",
            "Dimension": "Dimension 9",
            "Discount": "Discount 9",
            "Rating": "Rating 9",
            "Review Count": "Review Count 9"
        },
        {
            "Product ID": "RI1010",
            "Name": "Rings Design 10",
            "Category": "Rings",
            "Material": "Material 10",
            "Gemstone": "Gemstone 10",
            "Color": "Color 10",
            "Size": "Size 10",
            "Price": "$19.00",
            "Quantity": "Quantity 10",
            "SKU": "SKU 10",
            "Brand": "Brand 10",
            "Collection": "Collection 10",
            "Style": "Style 10",
            "Occasion": "Occasion 10",
            "Gender": "Gender 10",
            "Weight": "Weight 10",
            "Dimension": "Dimension 10",
            "Discount": "Discount 10",
            "Rating": "Rating 10",
            "Review Count": "Review Count 10"
        },
        {
            "Product ID": "RI1011",
            "Name": "Rings Design 11",
            "Category": "Rings",
            "Material": "Material 11",
            "Gemstone": "Gemstone 11",
            "Color": "Color 11",
            "Size": "Size 11",
            "Price": "$20.00",
            "Quantity": "Quantity 11",
            "SKU": "SKU 11",
            "Brand": "Brand 11",
            "Collection": "Collection 11",
            "Style": "Style 11",
            "Occasion": "Occasion 11",
            "Gender": "Gender 11",
            "Weight": "Weight 11",
            "Dimension": "Dimension 11",
            "Discount": "Discount 11",
            "Rating": "Rating 11",
            "Review Count": "Review Count 11"
        },
        {
            "Product ID": "RI1012",
            "Name": "Rings Design 12",
            "Category": "Rings",
            "Material": "Material 12",
            "Gemstone": "Gemstone 12",
            "Color": "Color 12",
            "Size": "Size 12",
            "Price": "$21.00",
            "Quantity": "Quantity 12",
            "SKU": "SKU 12",
            "Brand": "Brand 12",
            "Collection": "Collection 12",
            "Style": "Style 12",
            "Occasion": "Occasion 12",
            "Gender": "Gender 12",
            "Weight": "Weight 12",
            "Dimension": "Dimension 12",
            "Discount": "Discount 12",
            "Rating": "Rating 12",
            "Review Count": "Review Count 12"
        },
        {
            "Product ID": "RI1013",
            "Name": "Rings Design 13",
            "Category": "Rings",
            "Material": "Material 13",
            "Gemstone": "Gemstone 13",
            "Color": "Color 13",
            "Size": "Size 13",
            "Price": "$22.00",
            "Quantity": "Quantity 13",
            "SKU": "SKU 13",
            "Brand": "Brand 13",
            "Collection": "Collection 13",
            "Style": "Style 13",
            "Occasion": "Occasion 13",
            "Gender": "Gender 13",
            "Weight": "Weight 13",
            "Dimension": "Dimension 13",
            "Discount": "Discount 13",
            "Rating": "Rating 13",
            "Review Count": "Review Count 13"
        },
        {
            "Product ID": "RI1014",
            "Name": "Rings Design 14",
            "Category": "Rings",
            "Material": "Material 14",
            "Gemstone": "Gemstone 14",
            "Color": "Color 14",
            "Size": "Size 14",
            "Price": "$23.00",
            "Quantity": "Quantity 14",
            "SKU": "SKU 14",
            "Brand": "Brand 14",
            "Collection": "Collection 14",
            "Style": "Style 14",
            "Occasion": "Occasion 14",
            "Gender": "Gender 14",
            "Weight": "Weight 14",
            "Dimension": "Dimension 14",
            "Discount": "Discount 14",
            "Rating": "Rating 14",
            "Review Count": "Review Count 14"
        },
        {
            "Product ID": "RI1015",
            "Name": "Rings Design 15",
            "Category": "Rings",
            "Material": "Material 15",
            "Gemstone": "Gemstone 15",
            "Color": "Color 15",
            "Size": "Size 15",
            "Price": "$24.00",
            "Quantity": "Quantity 15",
            "SKU": "SKU 15",
            "Brand": "Brand 15",
            "Collection": "Collection 15",
            "Style": "Style 15",
            "Occasion": "Occasion 15",
            "Gender": "Gender 15",
            "Weight": "Weight 15",
            "Dimension": "Dimension 15",
            "Discount": "Discount 15",
            "Rating": "Rating 15",
            "Review Count": "Review Count 15"
        },
        {
            "Product ID": "RI1016",
            "Name": "Rings Design 16",
            "Category": "Rings",
            "Material": "Material 16",
            "Gemstone": "Gemstone 16",
            "Color": "Color 16",
            "Size": "Size 16",
            "Price": "$25.00",
            "Quantity": "Quantity 16",
            "SKU": "SKU 16",
            "Brand": "Brand 16",
            "Collection": "Collection 16",
            "Style": "Style 16",
            "Occasion": "Occasion 16",
            "Gender": "Gender 16",
            "Weight": "Weight 16",
            "Dimension": "Dimension 16",
            "Discount": "Discount 16",
            "Rating": "Rating 16",
            "Review Count": "Review Count 16"
        },
        {
            "Product ID": "RI1017",
            "Name": "Rings Design 17",
            "Category": "Rings",
            "Material": "Material 17",
            "Gemstone": "Gemstone 17",
            "Color": "Color 17",
            "Size": "Size 17",
            "Price": "$26.00",
            "Quantity": "Quantity 17",
            "SKU": "SKU 17",
            "Brand": "Brand 17",
            "Collection": "Collection 17",
            "Style": "Style 17",
            "Occasion": "Occasion 17",
            "Gender": "Gender 17",
            "Weight": "Weight 17",
            "Dimension": "Dimension 17",
            "Discount": "Discount 17",
            "Rating": "Rating 17",
            "Review Count": "Review Count 17"
        },
        {
            "Product ID": "RI1018",
            "Name": "Rings Design 18",
            "Category": "Rings",
            "Material": "Material 18",
            "Gemstone": "Gemstone 18",
            "Color": "Color 18",
            "Size": "Size 18",
            "Price": "$27.00",
            "Quantity": "Quantity 18",
            "SKU": "SKU 18",
            "Brand": "Brand 18",
            "Collection": "Collection 18",
            "Style": "Style 18",
            "Occasion": "Occasion 18",
            "Gender": "Gender 18",
            "Weight": "Weight 18",
            "Dimension": "Dimension 18",
            "Discount": "Discount 18",
            "Rating": "Rating 18",
            "Review Count": "Review Count 18"
        },
        {
            "Product ID": "RI1019",
            "Name": "Rings Design 19",
            "Category": "Rings",
            "Material": "Material 19",
            "Gemstone": "Gemstone 19",
            "Color": "Color 19",
            "Size": "Size 19",
            "Price": "$28.00",
            "Quantity": "Quantity 19",
            "SKU": "SKU 19",
            "Brand": "Brand 19",
            "Collection": "Collection 19",
            "Style": "Style 19",
            "Occasion": "Occasion 19",
            "Gender": "Gender 19",
            "Weight": "Weight 19",
            "Dimension": "Dimension 19",
            "Discount": "Discount 19",
            "Rating": "Rating 19",
            "Review Count": "Review Count 19"
        },
        {
            "Product ID": "RI1020",
            "Name": "Rings Design 20",
            "Category": "Rings",
            "Material": "Material 20",
            "Gemstone": "Gemstone 20",
            "Color": "Color 20",
            "Size": "Size 20",
            "Price": "$29.00",
            "Quantity": "Quantity 20",
            "SKU": "SKU 20",
            "Brand": "Brand 20",
            "Collection": "Collection 20",
            "Style": "Style 20",
            "Occasion": "Occasion 20",
            "Gender": "Gender 20",
            "Weight": "Weight 20",
            "Dimension": "Dimension 20",
            "Discount": "Discount 20",
            "Rating": "Rating 20",
            "Review Count": "Review Count 20"
        }
    ],
   
}